# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruote-jig}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Torsten Sch\303\266nebaum"]
  s.date = %q{2009-12-07}
  s.description = %q{A ruote 2.0 participant implementation using rufus-jig to notify HTTP interfaces (mostly JSON-aware) about workitems.}
  s.email = %q{torsten.schoenebaum@planquadrat-software.de}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "example.rb",
     "lib/ruote/jig/part/jig_participant.rb",
     "test/test.rb",
     "test/ut_0.rb"
  ]
  s.homepage = %q{http://github.com/tosch/ruote-jig}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruote participant using rufus-jig}
  s.test_files = [
    "test/test.rb",
     "test/ut_0.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruote>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<rufus-jig>, [">= 0.1.1"])
    else
      s.add_dependency(%q<ruote>, [">= 2.0.0"])
      s.add_dependency(%q<rufus-jig>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<ruote>, [">= 2.0.0"])
    s.add_dependency(%q<rufus-jig>, [">= 0.1.1"])
  end
end

